server:
  port: 8091

spring:
    application:
        name: gameley-config
    cloud:
        config:
            server:
                git:
                    uri: https://gitee.com/lwydyby/spring-boot-cloud
                    search-paths: config-repo
eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health

    client:
        serviceUrl:
            defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8090}/eureka/

security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}
