eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 5000
spring:
  application:
    name: gateway-service
#  sleuth:
#    sampler:                                    #日志记录
#      percentage: 1.0
#  zipkin:
#    base-url: http://localhost:9411
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: user-service
    api-b:
          path: /gameley-auth/**
          serviceId: gameley-auth
  prefix: /api #为zuul设置一个公共的前缀

gate:
  ignore:
    startWith: /static,/login,/gameley-auth/oauth/token

audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: restapiuser
  expiresSecond: 172800

jwt:
  header: token   #http请求头所需要的字段
  secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=      #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
