eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: restapiuser
  expiresSecond: 172800
server:
  port: 8765
spring:
  application:
    name: gameley-auth